### ISSUE TITLE
关于 v2ray plugin for shadowsocks

### ISSUE THREAD

**Issue by zozovo** [mritd/dockerfile#68]
很喜欢你的 images，用起来超方便。
可以考虑一下将 v2ray-plugin 集成到 shadowsocks 里面嘛？
https://github.com/shadowsocks/v2ray-plugin

**Comment by mritd** [comment]
@zozovo 已经集成，镜像 tag 为 `3.2.3-20181224`，请测试；如果没问题我将关闭这个 issue。

**Comment by Dreamacro** [comment]
```yml
version: '3'
services:
  ss:
    image: mritd/shadowsocks
    environment:
      - SS_MODULE=ss-server
      - SS_CONFIG=-s 0.0.0.0 -p 2334 -m chacha20 -k password --plugin v2ray-plugin --plugin-opts="server"
    ports:
      - "2334:2334"
    container_name: ss
```

log 输出
```
ss2   | Kcptun not started......
ss2   | Starting shadowsocks......
ss2   |  2019-01-31 17:39:44 INFO: plugin "v2ray-plugin" enabled
ss2   |  2019-01-31 17:39:44 INFO: initializing ciphers... chacha20
ss2   |  2019-01-31 17:39:44 INFO: tcp server listening at 127.0.0.1:33313
ss2   |  2019-01-31 17:39:44 INFO: running from root user
ss2   | 2019/01/31 17:39:44 V2Ray 4.13 (Po) Custom
ss2   | 2019/01/31 17:39:44 A unified platform for anti-censorship.
ss2   | 2019/01/31 17:39:44 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 33313 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:33313 > listen tcp 127.0.0.1:33313: bind: address already in use
ss2   |  2019-01-31 17:39:44 ERROR: plugin service exit unexpectedly
```

是我配置的有问题吗
