### ISSUE TITLE
使用 v2ray-plugin 开启 TLS 模式下，无法绑定 443 端口

### ISSUE THREAD

**Issue by sinoon** [mritd/dockerfile#97]
配置如下

```yaml
version: '3'
services:
  ss:
    image: mritd/shadowsocks
    environment:
      - SS_MODULE=ss-server
      - SS_CONFIG=-s 0.0.0.0 -p 443 -m chacha20 -k 9f1IK7NMq3Z9dwkb2B --plugin v2ray-plugin --plugin-opts=tls;server;host=mydoamin;fast-open;cert=/etc/letsencrypt/archive/mydoamin/fullchain1.pem;key=/etc/letsencrypt/archive/mydoamin/privkey1.pem
    volumes:
      - /etc/letsencrypt/archive/mydoamin/:/etc/letsencrypt/archive/mydoamin/
    ports:
      - "1984:1984"
      - "443:443"
      - "80:80"
    container_name: ss
```
错误信息如图：

![image](https://user-images.githubusercontent.com/6065488/69900891-1aa0ac80-13b4-11ea-8fe4-5aa1469706db.png)

经历了 cert 和 key 没有找到的问题，现在应该只剩下绑定问题了。推测是因为 entryport 的时候，没有以 root 身份开始吗？看错误是这个意思，但是我不知道如何修复这个问题。

作者可以帮我看下吗？
